#!/bin/bash

SELF=$(readlink -f "$0")
HERE=${SELF%/*}

"$HERE/proot" -R "$HERE/app" \
-b /usr/share/icons:/usr/share/icons \
-b /usr/share/fonts:/usr/share/fonts \
-b /usr/share/themes:/usr/share/themes \
/usr/bin/python3 /usr/bin/carburetor "$@" | cat

PID=$!
wait $PID

exit 0
