name: Build Carburetor AppImage
# Controls when the action will run.
on:
  # Build at 00:00 every 6th day
  schedule:
    - cron: "0 0 */6 * *"
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        
        sudo apt-get install -y \
          wget \
          file \
          desktop-file-utils \
          libfuse2 \
          libgtk-4-1 \
          libadwaita-1-0 \
          libgdk-pixbuf-2.0-0 \
          libgirepository-1.0-1 \
          gir1.2-adw-1 \
          gir1.2-gtk-4.0 \
          libglib2.0-bin \
          python3-pycountry \
          adwaita-icon-theme-full \
          appstream-util \
          debootstrap \
          schroot \
          bubblewrap \
          autoconf \
          coreutils \
          curl \
          zstd

    - name: Download rootfs and setup some stuff
      run: |
        chmod +x download_latest_debian_bootstrap.sh
        ./download_latest_debian_bootstrap.sh
        mkdir app
        mkdir arch
        tar xf rootfs-latest.tar.xz -C ./app/
        mv ./app/ arch/
        cp mount.sh ./arch/
        chmod +x ./arch/mount.sh
        sudo ./arch/mount.sh
        cp ${GITHUB_WORKSPACE}/files/AppRun ${GITHUB_WORKSPACE}/arch/
        chmod +x ${GITHUB_WORKSPACE}/arch/AppRun
        cp ${GITHUB_WORKSPACE}/files/io.frama.tractor.carburetor.svg -t ${GITHUB_WORKSPACE}/arch/
        cp ${GITHUB_WORKSPACE}/files/io.frama.tractor.carburetor.desktop -t ${GITHUB_WORKSPACE}/arch/
        cp ${GITHUB_WORKSPACE}/files/proot -t ${GITHUB_WORKSPACE}/arch/
        chmod +x -t ${GITHUB_WORKSPACE}/arch/proot

    - name: Pack AppImage
      run: |
        wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool && chmod +x appimagetool
        ARCH=x86_64 ./appimagetool -n ${GITHUB_WORKSPACE}/arch/root/

    - name: Delete Previous Release
      run: |
          gh release delete "${APP_VERSION}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag -y || echo "No release to delete"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
          name: "Continuous universal"
          tag_name: continuous-universal
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
