name: Build Carburetor AppImage
# Controls when the action will run.
on:
  # Build at 00:00 every 6th day
  schedule:
    - cron: "0 0 */6 * *"
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        
        sudo apt-get install -y \
          wget \
          file \
          desktop-file-utils \
          libfuse2 \
          libgtk-4-1 \
          libadwaita-1-0 \
          libgdk-pixbuf-2.0-0 \
          libgirepository-1.0-1 \
          gir1.2-adw-1 \
          gir1.2-gtk-4.0 \
          libglib2.0-bin \
          python3-pycountry \
          adwaita-icon-theme-full \
          appstream-util

    - name: Download appimage-builder
      run: |
        echo $PATH
        wget -q https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage -O appimagebuilder && chmod +x appimagebuilder
        ./appimagebuilder --recipe carburator.yml --skip-appimage

    - name: Pack AppImage
      run: |
        wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool && chmod +x appimagetool
        ARCH=x86_64 ./appimagetool -n AppDir/

    - name: Delete Previous Release
      run: |
          gh release delete "${APP_VERSION}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag -y || echo "No release to delete"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
          name: "Continuous universal"
          tag_name: continuous-universal
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
