name: Build Carburetor AppImage

permissions:
  contents: write

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: ubuntu:22.04
      options: --privileged

    steps:
    - name: Install system dependencies
      run: |
        apt-get update
        apt-get install -y \
          wget \
          file \
          desktop-file-utils \
          libfuse2 \
          libgtk-4-1 \
          libadwaita-1-0 \
          libgdk-pixbuf-2.0-0 \
          libgirepository-1.0-1 \
          gir1.2-adw-1 \
          gir1.2-gtk-4.0 \
          libglib2.0-bin \
          python3-pycountry \
          adwaita-icon-theme-full \
          appstream-util

    - name: Download appimage-builder
      run: |
        wget -q https://github.com/AppImageCrafters/appimage-builder/releases/download/v1.1.0/appimage-builder-1.1.0-x86_64.AppImage -O appimagebuilder && chmod +x appimagebuilder
        ./appimagebuilder --recipe carburator.yml --skip-appimage

    - name: Pack AppImage
      run: |
        wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool && chmod +x appimagetool
        cp io.frama.tractor.carburetor.desktop ./AppDir/
        cp io.frama.tractor.carburetor.svg ./AppDir/
        ARCH=x86_64 ./appimagetool -n AppDir/

    - name: Upload AppImage as artifact
      uses: actions/upload-artifact@v4
      with:
        name: Carburetor.AppImage
        path: Carburetor-linux-x86_64.AppImage

    - name: Release AppImage
      uses: softprops/action-gh-release@v1
      with:
        files: '*.AppImage*'
