name: Build Carburetor AppImage
# Controls when the action will run.
on:
  # Build at 00:00 every 6th day
  schedule:
    - cron: "0 0 */6 * *"
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]
  pull_request:
    branches: [ main ]
    paths-ignore: [ '**/README.md' ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v4
    - name: Install system dependencies
      run: |
        
        sudo apt-get install -y \
          wget \
          file \
          desktop-file-utils \
          libfuse2 \
          libgtk-4-1 \
          libadwaita-1-0 \
          libgdk-pixbuf-2.0-0 \
          libgirepository-1.0-1 \
          gir1.2-adw-1 \
          gir1.2-gtk-4.0 \
          libglib2.0-bin \
          python3-pycountry \
          adwaita-icon-theme-full \
          appstream-util \
          debootstrap \
          schroot \
          bubblewrap \
          autoconf \
          coreutils

    - name: Download rootfs and setup some stuff
      run: |
        wget -c "https://archive.archlinux.org/iso/"
        cat index.html | tail -n 3 | awk '{print $2}' | cut -d "/" -f 1 | cut -d "\"" -f 2 | xargs -i -t -exec wget -r --no-parent np -l 1 -A "*.zst" -erobots=off -P . "https://archive.archlinux.org/iso/{}/archlinux-bootstrap-x86_64.tar.zst"
        find ${GITHUB_WORKSPACE} -name '*.zst' | xargs -i -t -exec mv {} ${GITHUB_WORKSPACE}
        mkdir arch
        tar xf archlinux-bootstrap-x86_64.tar.zst -C ./arch/
        # criar no github uma nova pasta parao AppRun e demais arquivos.
        cp /etc/resolv.conf -t ${GITHUB_WORKSPACE}/arch/root.x86_64/etc/ && cp ${GITHUB_WORKSPACE}/files/mirrorlist -t ${GITHUB_WORKSPACE}/arch/root.x86_64/etc/pacman.d/ && cp ${GITHUB_WORKSPACE}/files/pacman.conf -t ${GITHUB_WORKSPACE}/arch/root.x86_64/etc/
        cd ${GITHUB_WORKSPACE}
        sudo chroot ./arch/root.x86_64/ /usr/bin/bash -c "pacman -Syyu --noconfirm && pacman -S carburetor tractor gsettings-desktop-schemas adwaita-icon-theme gnome-icon-theme --noconfirm && pacman -Scc --noconfirm && rm -rf /var/cache/pacman/pkg/* && sed -i '18,516 s/^#//' /etc/locale.gen && locale-gen"
        cp ${GITHUB_WORKSPACE}/files/AppRun ${GITHUB_WORKSPACE}/arch/ && chmod a+x ${GITHUB_WORKSPACE}/arch/AppRun && cp ${GITHUB_WORKSPACE}/files/io.frama.tractor.carburetor.svg -t ${GITHUB_WORKSPACE}/arch/ && cp ${GITHUB_WORKSPACE}/files/io.frama.tractor.carburetor.desktop -t ${GITHUB_WORKSPACE}/arch/ && cp ${GITHUB_WORKSPACE}/files/proot -t ${GITHUB_WORKSPACE}/arch/ && chmod a+x -t ${GITHUB_WORKSPACE}/arch/proot
        mv ${GITHUB_WORKSPACE}/arch/root.x86_64/  ${GITHUB_WORKSPACE}/arch/root/

    - name: Pack AppImage
      run: |
        wget -q https://github.com/AppImage/appimagetool/releases/download/continuous/appimagetool-x86_64.AppImage -O appimagetool && chmod +x appimagetool
        ARCH=x86_64 ./appimagetool -n ${GITHUB_WORKSPACE}/arch/root/

    - name: Delete Previous Release
      run: |
          gh release delete "${APP_VERSION}" --repo "${GITHUB_REPOSITORY}" --cleanup-tag -y || echo "No release to delete"
      env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      continue-on-error: true

    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
          name: "Continuous universal"
          tag_name: continuous-universal
          prerelease: false
          draft: false
          generate_release_notes: false
          make_latest: true
          files: |
            *.AppImage*
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
